{{- if .Values.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "flux-drift-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flux-drift-webhook.labels" . | nindent 4 }}
    {{- with .Values.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "flux-drift-webhook.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      path: {{ .Values.podMonitor.path }}
      interval: {{ .Values.podMonitor.interval }}
{{- end }}
